post http://localhost:3000/api/v1/tickets/reserve
Content-Type: application/json

{
  "eventId": "event_1",
  "seatId": "A-1",
  "userId": "user_1"
}


###

post http://localhost:3000/api/v1/tickets/confirm
Content-Type: application/json

{
  "reservationId": "d5dc83da-36c1-410f-abff-12e29c22a977",
  "idempotencyKey": "uniqKey_500"
}