post http://localhost:3000/api/v1/tickets/reserve
Content-Type: application/json

{
  "eventId": "event_1",
  "seatId": "seat_1",
  "userId": "user_1"
}


###

post http://localhost:3000/api/v1/tickets/confirm
Content-Type: application/json

{
  "reservationId": "9a109fa4-f0da-414e-b208-42ff941404a1",
  "idempotencyKey": "uniqKey_1"
}